# Check `docs/pipeline.md` to get info about this file

resources:
- name: .-repository
  type: git
  source:
    uri: https://github.com/calj/..git
    branch: master

- name: .-image
  type: docker-image
  source:
    repository: calj/.
    username: {{docker_username}}
    password: {{docker_password}}

jobs:
- name: .
  serial: true
  plan:
  - get: .-repository
    trigger: true
  - put: .-image
    params:
      build: .-repository
